app: GenericHashTable.c main.c
	gcc -c main.c -o main.o -Wall -Wvla -g 
	gcc -c GenericHashTable.c -o GenericHashTable.o -Wall -Wvla -g 
	gcc GenericHashTable.o main.o -o run -Wall -Wvla -g 
	rm GenericHashTable.o main.o
